config/routes.rb
TravelC::Application.routes.draw do

  root to: "top#index"

  resources :countries, :only => [:index, :show] do
    collection { get "search" }
  end

  resources :cities, :only => [:index, :show] do
    collection { get "search" }
  end

  resources :foods, :only => [:index, :show] do
    collection { get "search" }
  end

  resources :results, :only => [:index]

  namespace :admin do
    resources :countries
    resources :spots
    resources :cities
    resources :foods
  end


  resources :admin, :only => [:index], :as => :admin


end

app/models/airport.rb
class Airport < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/airports.rb
class Airports < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/area.rb
class Area < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/areas.rb
class Areas < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name, :area_id, :city_ranking, :imagephoto, :country_id, :tags_attributes
  attr_accessible :name, :area_id, :city_ranking, :imagephoto, :country_id, :is_admin, :as => :admin

  belongs_to :country

end

app/models/climate.rb
class Climate < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/climates.rb
class Climates < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name, :language, :capital, :area_id, :popular_ranking, :imagephoto, :googlemap, :tags_attributes
  attr_accessible :name, :capital, :language, :area_id, :popular_ranking, :imagephoto, :googlemap, :is_admin, :as => :admin

  has_many :spots
  has_many :cities

  class << self
      def search(query)
        rel = order("id")
        if query.present?
          rel = rel.where("name LIKE ?",
                  "%#{query}%")
        end
      rel
      end
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :name,:country_id,:food_category_id, :tags_attributes
  attr_accessible :name,:country_id,:food_category_id, :is_admin, :as => :admin
end

app/models/food_category.rb
class FoodCategory < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/food_culture.rb
class FoodCulture < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/foods.rb
class Foods < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/heritage_category.rb
class HeritageCategory < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/price.rb
class Price < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  attr_accessible :name, :area_id, :spot_category_id,:country_id, :tags_attributes
  attr_accessible :name, :area_id, :spot_category_id,:country_id, :is_admin, :as => :admin

  belongs_to :country
  
end

app/models/spot_category.rb
class SpotCategory < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/spots.rb
class Spots < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/traffic.rb
class Traffic < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/traffics.rb
class Traffics < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/world_heritage.rb
class WorldHeritage < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < ApplicationController

  def index
    @countries = Country.order("id")
  end

  def show
    @country = Country.find(params[:id])
  end

  def new
    @country = Country.new
  end

  def edit
    @country = Country.find(params[:id])
  end

  def create
    @country = Country.new(params[:country], :as => :admin)
      if @country.save
        redirect_to [:admin, @country], notice: 'Country was successfully created.'
      else
        render 'new'
      end
  end

  def update
    @country = Country.find(params[:id])
      if @country.update_attributes(name: params["country"]["name"],capital: params["country"]["capital"])
        redirect_to [:admin, @country], notice: 'Country was successfully updated.'
      else
        render 'edit'
      end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy
    redirect_to [:admin, @country], notice: 'Country deleted.'

  end

    def country_params
      params.require(:country).permit(:name, :language, :capital, :area_id, :popular_ranking, :imagephoto, :googlemap)
    end


end

app/controllers/countries_controller.rb
# coding: utf-8

class CountriesController < ApplicationController
  # 国一覧
  def index
    @countries = Country.order("id")
  end

  # 国ID検索
  def search
    @countries = Country.search(params[:q])
    render "index"
  end

  # 国の詳細
  def show
    @country = Country.find(params[:id])
  end

end

app/views/admin/countries/edit.html.erb
<% @page_title = "国情報の編集" %>

<h1><%= @page_title %></h1>

<%= form_for([:admin,@country]) do |f| %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
<br>
      <div class="field">
        <%= f.label :capital %><br>
        <%= f.text_field :capital %>
      </div>
<br>
      <div class="actions">
        <%= f.submit %>
      </div>
<% end %>

<p><%= link_to "国の詳細に戻る", admin_country_path(@country) %></p>

app/views/admin/countries/index.html.erb
<% @page_title = "国一覧" %>

<h1><%= @page_title %></h1>

<p><%= link_to "国の新規登録", :new_admin_country %></p>

<table class="list2">
  <tr>
    <th>ID.</th>
    <th>国名</th>
    <th>修正</th>
  </tr>

  <% @countries.each do |country| %>
  <tr>
    <td align="right"><%= country.id %></td>
    <td><%= link_to country.name, admin_country_path(country.id) %></td>
    <td style="display:inline-flex">
      <%= link_to "詳細", admin_country_path(country.id) %>
      &ensp;|&ensp;
      <%= link_to "編集", edit_admin_country_path(country.id) %>
      &ensp;|&ensp;
      <%= link_to "削除", [:admin, country], method: :delete,
          confirm: "本当に削除しますか?" %>
    </td>
  </tr>
  <% end %>

</table>

<br><br><br>

app/views/admin/countries/new.html.erb
<% @page_title = "国情報の新規登録" %>

<h1><%= @page_title %></h1>

<%= form_for([:admin,@country]) do |f| %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
<br>
      <div class="field">
        <%= f.label :language %><br>
        <%= f.text_field :language %>
      </div>
<br>
      <div class="field">
        <%= f.label :capital %><br>
        <%= f.text_field :capital %>
      </div>
<br>
      <div class="field">
        <%= f.label :area_id %><br>
        <%= f.number_field(:area_id, in: 1..8, step: 1) %>
      </div>
<br>
      <div class="field">
        <%= f.label :popular_ranking %><br>
        <%= f.text_field :popular_ranking %>
      </div>
<br>
      <div class="actions">
        <%= f.submit %>
      </div>
<% end %>

app/views/admin/countries/show.html.erb
<% @page_title = "国詳細" %>

<h1><%= @page_title %></h1>

<table class="attr">
  <tr>
    <th width="150">ID</th>
    <td><%= @country.id %></td>
  </tr>
  <tr>
    <th>国名</th>
    <td><%= @country.name %></td>
  </tr>
  <tr>
    <th>首都</th>
    <td><%= @country.capital %></td>
  </tr>
  <tr>
    <th>言語</th>
    <td><%= @country.language %></td>
  </tr>
  </table>

  <section class="ed">
  <tr>
    <td>
      <%= link_to "編集", edit_admin_country_path(@country.id) %>
      &ensp;|&ensp;
      <%= link_to "削除", [:admin, @country], method: :delete,
          confirm: "本当に削除しますか?" %>
    </td>
  </tr>
</section>

<p><%= link_to "国の一覧に戻る", admin_countries_path(@countries) %></p>